openapi: 3.0.4
info:
  title: Resource statuses log models
  description: Log models for logging services of resource statuses
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        statuses:
          $ref: '#/components/schemas/ResourceStatusesLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    ResourceStatusesLogModel:
      title: Модель лога для микросервиса статуса ресурсов
      type: object
      properties:
        requestId:
          type: string
        operation:
          $ref: '#/components/schemas/LogOperation'
        request:
          $ref: '#/components/schemas/Log'
        requestFilter:
          $ref: '#/components/schemas/FilterLog'
        response:
          $ref: '#/components/schemas/Log'
        responses:
          type: array
          items:
            $ref: '#/components/schemas/Log'

    LogOperation:
      type: string
      enum:
        - create
        - read
        - update
        - delete
        - search
        - offers
        - init
        - finish

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    Log:
      title: Модель лога для объявления
      type: object
      properties:
        id:
          type: string
        resourceType:
          type: string
        status:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string



    FilterLog:
      title: Модель лога фильтра
      properties:
        id:
          type: string
        resourceType:
          type: string
        status:
          type: string
        ownerId:
          type: string

